# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fobi', '0012_auto_20161109_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='formwizardentry',
            name='show_all_navigation_buttons',
            field=models.BooleanField(default=False, help_text='Show all navigation buttons.', verbose_name='Show all navigation buttons?'),
        ),
    ]
