# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fobi', '0014_auto_20170516_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='formentry',
            name='active_date_from',
            field=models.DateTimeField(blank=True, help_text="Date and time when the form becomes active in the format: 'YYYY-MM-DD HH:MM'. Leave it blank to activate immediately.", null=True, verbose_name='Active from'),
        ),
        migrations.AddField(
            model_name='formentry',
            name='active_date_to',
            field=models.DateTimeField(blank=True, help_text="Date and time when the form becomes inactive in the format: 'YYYY-MM-DD HH:MM'. Leave it blank to keep active forever.", null=True, verbose_name='Active until'),
        ),
        migrations.AddField(
            model_name='formentry',
            name='inactive_page_message',
            field=models.TextField(blank=True, help_text='Custom message text to display if form is inactive.', null=True, verbose_name='Inactive form page body'),
        ),
        migrations.AddField(
            model_name='formentry',
            name='inactive_page_title',
            field=models.CharField(blank=True, help_text='Custom message title to display if form is inactive.', max_length=255, null=True, verbose_name='Inactive form page title'),
        ),
    ]
