# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-10 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fobi', '0014_auto_20170516_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='formentry',
            name='has_invisible_recaptcha',
            field=models.BooleanField(default=False, help_text='Spam and abuse protection service from Google. Requires a valid API key.', verbose_name='Invisible reCAPTCHA?'),
        ),
    ]
