# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fobi', '0014_auto_20170516_1413'),
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FobiFormWidget',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='fobi_contrib_apps_djangocms_integration_fobiformwidget', serialize=False, to='cms.CMSPlugin')),
                ('form_template_name', models.CharField(blank=True, help_text='Template to render the form with.', max_length=255, null=True, verbose_name='Form template name')),
                ('hide_form_title', models.BooleanField(default=False, help_text='If checked, no form title is shown.', verbose_name='Hide form title')),
                ('form_title', models.CharField(blank=True, help_text='Overrides the default form title.', max_length=255, null=True, verbose_name='Form title')),
                ('form_submit_button_text', models.CharField(blank=True, help_text='Overrides the default form submit button text.', max_length=255, null=True, verbose_name='Submit button text')),
                ('success_page_template_name', models.CharField(blank=True, help_text='Template to render the success page with.', max_length=255, null=True, verbose_name='Success page template name')),
                ('hide_success_page_title', models.BooleanField(default=False, help_text='If checked, no success page title is shown.', verbose_name='Hide success page title')),
                ('success_page_title', models.CharField(blank=True, help_text='Overrides the default success page title.', max_length=255, null=True, verbose_name='Succes page title')),
                ('success_page_text', models.TextField(blank=True, help_text='Overrides the default success page text.', null=True, verbose_name='Succes page text')),
                ('form_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fobi.FormEntry', verbose_name='Form')),
            ],
            options={
                'db_table': 'djangocms_integration_fobiformwidget',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
