# -*- coding: utf-8 -*-
# Generated by Django 3.2.11 on 2022-07-14 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fobi_contrib_plugins_form_handlers_db_store', '0002_savedformwizarddataentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedformwizarddataentry',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated', auto_now=True),
        ),   
        migrations.AddField(
            model_name='savedformdataentry',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated', auto_now=True),
        ),     
    ]
