# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='language',
        ),
        migrations.RemoveField(
            model_name='page',
            name='translation_of',
        ),
        migrations.AddField(
            model_name='page',
            name='creation_date',
            field=models.DateTimeField(editable=False, null=True, verbose_name='creation date'),
        ),
        migrations.AddField(
            model_name='page',
            name='modification_date',
            field=models.DateTimeField(editable=False, null=True, verbose_name='modification date'),
        ),
        migrations.AlterField(
            model_name='fobiformwidget',
            name='form_template_name',
            field=models.CharField(blank=True, choices=[('fobi/bootstrap3_extras/view_embed_form_entry_ajax.html', 'Custom bootstrap3 embed form view template')], help_text='Template to render the form with.', max_length=255, null=True, verbose_name='Form template name'),
        ),
        migrations.AlterField(
            model_name='fobiformwidget',
            name='success_page_template_name',
            field=models.CharField(blank=True, choices=[('fobi/bootstrap3_extras/embed_form_entry_submitted_ajax.html', 'Custom bootstrap3 embed form entry submitted template')], help_text='Template to render the success page with.', max_length=255, null=True, verbose_name='Success page template name'),
        ),
        migrations.AlterField(
            model_name='page',
            name='template_key',
            field=models.CharField(choices=[('page_base', 'Base template')], default='page_base', max_length=255, verbose_name='template'),
        ),
    ]
