# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-14 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fobi', '0014_auto_20170516_1413'),
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='FobiFormPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('form_template_name', models.CharField(blank=True, choices=[('fobi/bootstrap3_extras/view_embed_form_entry_ajax.html', 'Custom bootstrap3 embed form view template')], help_text='Choose an alternative template to render the form with. Leave blank to use the default for this page type (e.g. fobi_form_page.html).', max_length=255, null=True, verbose_name='Form template name')),
                ('hide_form_title', models.BooleanField(default=False, help_text='If checked, no form title is shown.', verbose_name='Hide form title')),
                ('form_title', models.CharField(blank=True, help_text='Overrides the default form title.', max_length=255, null=True, verbose_name='Form title')),
                ('form_submit_button_text', models.CharField(blank=True, help_text='Overrides the default form submit button text.', max_length=255, null=True, verbose_name='Submit button text')),
                ('success_page_template_name', models.CharField(blank=True, choices=[('fobi/bootstrap3_extras/embed_form_entry_submitted_ajax.html', 'Custom bootstrap3 embed form entry submitted template')], help_text='Choose an alternative template to render the success page with. Leave blank to use the default for this page type (e.g. fobi_form_page_success.html).', max_length=255, null=True, verbose_name='Success page template name')),
                ('hide_success_page_title', models.BooleanField(default=False, help_text='If checked, no success page title is shown.', verbose_name='Hide success page title')),
                ('success_page_title', models.CharField(blank=True, help_text='Overrides the default success page title.', max_length=255, null=True, verbose_name='Success page title')),
                ('success_page_text', models.TextField(blank=True, help_text='Overrides the default success page text.', null=True, verbose_name='Success page text')),
                ('form_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fobi.FormEntry', verbose_name='Form')),
            ],
            options={
                'verbose_name': 'Fobi form page',
                'verbose_name_plural': 'Fobi form pages',
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
